// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtEoOAxCs4vapMaODd9GBmGqvWZFs6RSI',
    appId: '1:298517615242:android:dfe549c3248556a70f1373',
    messagingSenderId: '298517615242',
    projectId: 'yolk-a-day',
    storageBucket: 'yolk-a-day.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIjsCqqhMEPxFpOhKMr0_-3bhCY4FarVI',
    appId: '1:298517615242:ios:9089ef572a7344bb0f1373',
    messagingSenderId: '298517615242',
    projectId: 'yolk-a-day',
    storageBucket: 'yolk-a-day.appspot.com',
    androidClientId: '298517615242-5g5aji713s02k7vesqnherm0ucsvm0ti.apps.googleusercontent.com',
    iosClientId: '298517615242-iel9aqi9f8ddukljsdsl68uo079ttvle.apps.googleusercontent.com',
    iosBundleId: 'com.gudetama.yolkADay',
  );
}
